var timetables = {
    IPCMB: [
        {
            time: "9:30 - 10:30",
            Monday: "BIO/CS",
            Tuesday: "PHY",
            Wednesday: "MATHS",
            Thursday: "MATHS",
            Friday: "KAN",
            Saturday: "PHY",
        },
        {
            time: "10:30 - 11:30",
            Monday: "PHY",
            Tuesday: "CHEM",
            Wednesday: "CHEM",
            Thursday: "BIO/CS",
            Friday: "CHEM",
            Saturday: "ENG",
        },
        {
            time: "11:30 - 12:30",
            Monday: "KAN",
            Tuesday: "ENG",
            Wednesday: "PHY",
            Thursday: "CHEM",
            Friday: "MATHS",
            Saturday: "KAN",
        },
        {
            time: "12:30 - 1:00",
            Monday: "Lunch Break",
            Tuesday: "Lunch Break",
            Wednesday: "Lunch Break",
            Thursday: "Lunch Break",
            Friday: "Lunch Break",
            Saturday: "Lunch Break",
        },
        {
            time: "1:00 - 2:00",
            Monday: "ENG",
            Tuesday: "BIO/CS",
            Wednesday: "ENG",
            Thursday: "KAN",
            Friday: "BIO/CS",
            Saturday: "MATHS",
        },
        {
            time: "2:00 - 3:00",
            Monday: "P/C",
            Tuesday: "MATHS",
            Wednesday: "MATHS",
            Thursday: "P/C",
            Friday: "BIO/CS",
            Saturday: "LAB",
        },

        // ... more rows for Class 1
    ],
    IIPCMB: [
        {
            time: "9:30 - 10:30",
            Monday: "MATHS",
            Tuesday: "CHEM",
            Wednesday: "CHEM",
            Thursday: "CHEM",
            Friday: "BIO/CS",
            Saturday: "ENG",
        },
        {
            time: "10:30 - 11:30",
            Monday: "CHEM",
            Tuesday: "MATHS",
            Wednesday: "KAN",
            Thursday: "ENG",
            Friday: "KAN",
            Saturday: "BIO/CS",
        },
        {
            time: "11:30 - 12:30",
            Monday: "ENG",
            Tuesday: "BIO/CS",
            Wednesday: "MATHS",
            Thursday: "PHY",
            Friday: "PHY",
            Saturday: "MATHS",
        },
        {
            time: "12:30 - 1:00",
            Monday: "Lunch Break",
            Tuesday: "Lunch Break",
            Wednesday: "Lunch Break",
            Thursday: "Lunch Break",
            Friday: "Lunch Break",
            Saturday: "Lunch Break",
        },
        {
            time: "1:00 - 2:00",
            Monday: "KAN",
            Tuesday: "KAN",
            Wednesday: "PHY",
            Thursday: "MATHS",
            Friday: "ENG",
            Saturday: "PHY",
        },
        {
            time: "2:00 - 3:00",
            Monday: "BIO/CS",
            Tuesday: "PHY",
            Wednesday: "P/C",
            Thursday: "BIO/CS",
            Friday: "P/C",
            Saturday: "KAN",
        },
        // ... more rows for Class 2
    ],
    IHEBA: [
        {
            time: "9:30 - 10:30",
            Monday: "HIS",
            Tuesday: "BS",
            Wednesday: "ECO",
            Thursday: "HIS",
            Friday: "KAN",
            Saturday: "BS",
        },
        {
            time: "10:30 - 11:30",
            Monday: "BIS",
            Tuesday: "ECO",
            Wednesday: "ACC",
            Thursday: "ECO",
            Friday: "ECO",
            Saturday: "ENG",
        },
        {
            time: "11:30 - 12:30",
            Monday: "KAN",
            Tuesday: "ENG",
            Wednesday: "HIS",
            Thursday: "BS",
            Friday: "HIS",
            Saturday: "KAN",
        },
        {
            time: "12:30 - 1:00",
            Monday: "Lunch Break",
            Tuesday: "Lunch Break",
            Wednesday: "Lunch Break",
            Thursday: "Lunch Break",
            Friday: "Lunch Break",
            Saturday: "Lunch Break",
        },
        {
            time: "1:00 - 2:00",
            Monday: "ENG",
            Tuesday: "ACC",
            Wednesday: "ENG",
            Thursday: "KAN",
            Friday: "ACC",
            Saturday: "ACC",
        },
        {
            time: "2:00 - 3:00",
            Monday: "ACC",
            Tuesday: "HIS",
            Wednesday: "KAN",
            Thursday: "ACC",
            Friday: "BS",
            Saturday: "ECO",
        },
    ],
    IIHEBA: [
        {
            time: "9:30 - 10:30",
            Monday: "ENG",
            Tuesday: "HIS",
            Wednesday: "BS",
            Thursday: "KAN",
            Friday: "HIS",
            Saturday: "ENG",
        },
        {
            time: "10:30 - 11:30",
            Monday: "KAN",
            Tuesday: "ACC",
            Wednesday: "ECO",
            Thursday: "BS",
            Friday: "ENG",
            Saturday: "ECO",
        },
        {
            time: "11:30 - 12:30",
            Monday: "B.S",
            Tuesday: "BS",
            Wednesday: "KAN",
            Thursday: "ACO",
            Friday: "ECO",
            Saturday: "ACC",
        },
        {
            time: "12:30 - 1:00",
            Monday: "Lunch Break",
            Tuesday: "Lunch Break",
            Wednesday: "Lunch Break",
            Thursday: "Lunch Break",
            Friday: "Lunch Break",
            Saturday: "Lunch Break",
        },
        {
            time: "1:00 - 2:00",
            Monday: "ACC",
            Tuesday: "ECO",
            Wednesday: "ENG",
            Thursday: "HIS",
            Friday: "KAN",
            Saturday: "HIS",
        },
        {
            time: "2:00 - 3:00",
            Monday: "ECO",
            Tuesday: "KAN",
            Wednesday: "HIS",
            Thursday: "ENG",
            Friday: "ACC",
            Saturday: "BS",
        },
    ],
    ICEBA: [
        {
            time: "9:30 - 10:30",
            Monday: "CS",
            Tuesday: "ECO",
            Wednesday: "KAN",
            Thursday: "KAN",
            Friday: "ENG",
            Saturday: "ECO",
        },
        {
            time: "10:30 - 11:30",
            Monday: "ACC",
            Tuesday: "BS",
            Wednesday: "BS",
            Thursday: "CS",
            Friday: "BS",
            Saturday: "KAN",
        },
        {
            time: "11:30 - 12:30",
            Monday: "ECO",
            Tuesday: "ACC",
            Wednesday: "ACC",
            Thursday: "ENG",
            Friday: "KAN",
            Saturday: "BS",
        },
        {
            time: "12:30 - 1:00",
            Monday: "Lunch Break",
            Tuesday: "Lunch Break",
            Wednesday: "Lunch Break",
            Thursday: "Lunch Break",
            Friday: "Lunch Break",
            Saturday: "Lunch Break",
        },
        {
            time: "1:00 - 2:00",
            Monday: "ENG",
            Tuesday: "CS",
            Wednesday: "ECO",
            Thursday: "ACC",
            Friday: "CS",
            Saturday: "ENG",
        },
        {
            time: "2:00 - 3:00",
            Monday: "BS",
            Tuesday: "KAN",
            Wednesday: "ENG",
            Thursday: "LAB",
            Friday: "ECO",
            Saturday: "ACC",
        },
    ],
    // Repeat the pattern for other classes
    IICEBA: [
        {
            time: "9:30 - 10:30",
            Monday: "BS",
            Tuesday: "ENG",
            Wednesday: "KAN",
            Thursday: "ECO",
            Friday: "CS",
            Saturday: "ACC",
        },
        {
            time: "10:30 - 11:30",
            Monday: "KAN",
            Tuesday: "KAN",
            Wednesday: "ENGs",
            Thursday: "ACC",
            Friday: "ACC",
            Saturday: "CS",
        },
        {
            time: "11:30 - 12:30",
            Monday: "ACC",
            Tuesday: "CS",
            Wednesday: "BS",
            Thursday: "KAN",
            Friday: "ENG",
            Saturday: "KAN",
        },
        {
            time: "12:30 - 1:00",
            Monday: "Lunch Break",
            Tuesday: "Lunch Break",
            Wednesday: "Lunch Break",
            Thursday: "Lunch Break",
            Friday: "Lunch Break",
            Saturday: "Lunch Break",
        },
        {
            time: "1:00 - 2:00",
            Monday: "ECO",
            Tuesday: "BS",
            Wednesday: "ECO",
            Thursday: "ENG",
            Friday: "BS",
            Saturday: "ECO",
        },
        {
            time: "2:00 - 3:00",
            Monday: "CS",
            Tuesday: "ECO",
            Wednesday: "ACC",
            Thursday: "BS",
            Friday: "LAB",
            Saturday: "ENG",
        },
    ],
    IHEPS: [
        {
            time: "9:30 - 10:30",
            Monday: "KAN",
            Tuesday: "PS",
            Wednesday: "HIS",
            Thursday: "ENG",
            Friday: "KAN",
            Saturday: "PS",
        },
        {
            time: "10:30 - 11:30",
            Monday: "ENG",
            Tuesday: "KAN",
            Wednesday: "PS",
            Thursday: "SOC",
            Friday: "SOC",
            Saturday: "HIS",
        },
        {
            time: "11:30 - 12:30",
            Monday: "SOC",
            Tuesday: "ENG",
            Wednesday: "ECO",
            Thursday: "HIS",
            Friday: "PS",
            Saturday: "ENG",
        },
        {
            time: "12:30 - 1:00",
            Monday: "Lunch Break",
            Tuesday: "Lunch Break",
            Wednesday: "Lunch Break",
            Thursday: "Lunch Break",
            Friday: "Lunch Break",
            Saturday: "Lunch Break",
        },
        {
            time: "1:00 - 2:00",
            Monday: "ECO",
            Tuesday: "HIS",
            Wednesday: "KAN",
            Thursday: "ECO",
            Friday: "ECO",
            Saturday: "SOC",
        },
        {
            time: "2:00 - 3:00",
            Monday: "HIS",
            Tuesday: "ECO",
            Wednesday: "SOC",
            Thursday: "PS",
            Friday: "ENG",
            Saturday: "KAN",
        },
    ],
    IIHEPS: [
        {
            time: "9:30 - 10:30",
            Monday: "ENG",
            Tuesday: "HIS",
            Wednesday: "SOC",
            Thursday: "KAN",
            Friday: "HIS",
            Saturday: "ENG",
        },
        {
            time: "10:30 - 11:30",
            Monday: "KAN",
            Tuesday: "SOC",
            Wednesday: "ECO",
            Thursday: "PS",
            Friday: "ENG",
            Saturday: "ECO",
        },
        {
            time: "11:30 - 12:30",
            Monday: "PS",
            Tuesday: "PS",
            Wednesday: "KAN",
            Thursday: "SOC",
            Friday: "ECO",
            Saturday: "SOC",
        },
        {
            time: "12:30 - 1:00",
            Monday: "Lunch Break",
            Tuesday: "Lunch Break",
            Wednesday: "Lunch Break",
            Thursday: "Lunch Break",
            Friday: "Lunch Break",
            Saturday: "Lunch Break",
        },
        {
            time: "1:00 - 2:00",
            Monday: "SOC",
            Tuesday: "ECO",
            Wednesday: "ENG",
            Thursday: "HIS",
            Friday: "KAN",
            Saturday: "HIS",
        },
        {
            time: "2:00 - 3:00",
            Monday: "ECO",
            Tuesday: "KAN",
            Wednesday: "HIS",
            Thursday: "ENG",
            Friday: "PS",
            Saturday: "PS",
        },
    ],
};